[package]
name = "ocm-parser"
version = "0.1.0"
edition = "2021"
description = "Parser for the graph datasets"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winnow = "0.5.37"
