[package]
name = "ocm-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ocm-parser = { path = "../ocm-parser" }
ordered-float = "4.2.0"
